---
title: "Submittr authentication by database"
output: html_document
runtime: shiny_prerendered
---

<!-- You can compile this file on its own to test your database connection.
  -- There MUST be a file in the directory named `dbkeys` which contains the 
     database login information. See 
     system.file("dbkeys-example.yml", package = "submittr")
     for the format
     -->

```{r setup-login, include = FALSE}
library(submittr)
#Formatting the credential boxes to be side-by-side
textInputRow<-function (inputId, label, value = "", type = "text",
                        message_after = "", message_before = "") 
{
    div(style="display:inline-block;",
        message_before,
        tags$label(label, `for` = inputId), 
        tags$input(id = inputId, type = type, value = value,class="input-small"),
        message_after)
}
```

******************

```{r echo = FALSE}
textInputRow("user_name", "Login ID:")
tmp <- textOutput("login_success", inline = TRUE)
textInputRow("password", "Passwd:", type = "password", message_after = tmp)
```

******************


```{r echo = FALSE, context = "server"}
# Connect to the database server. You can customize the name of the table for 
# storing the submissions, as well as the name of the table holding student login 
# passwords. 
options(tutorial.event_recorder = 
          submittr::create_submit_to_db(table_name = "higgins",
                              password_table_name = "passwords"))
# Shiny logic
output$login_success <- renderText({"Please log in."})
output$login_success <-
  renderText({
    Accounts <- submittr:::db_info$Password_table
    id <- input$user_name
    password <- input$password
    if (is.null(Accounts)) return("No accounts set up yet.")
    else {
      ind <- which(id == Accounts$user)
      if (length(ind) > 0) {
        if (password == Accounts$passwd[ind[1]] ) {
          submittr::set_user(id, Accounts$role[ind[1]], Accounts$group[ind[1]])
          return("Login successful.")
        } else {
          submittr::clear_user() # accept entries, but no user id
          return("Wrong password!")
        }
      } else {
        submittr::clear_user() # accept entries, but no user id
        return("Invalid user id.")
      }
    }
  })
```
